"""End-to-end golden-vector test: checked-in image -> preprocess -> ONNX
inference must reproduce the reference embedding recorded from the PyTorch
tower (tests/golden/golden_embedding.json, generated by
tests/golden/generate_reference.py on a machine with the model-conversion venv).

Catches preprocessing drift (BGRA swizzle, resize, normalization mistakes)
that pure graph parity can't see. Skips when the gitignored .onnx artifact
hasn't been built (run model-conversion/export_onnx.py first).
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

GOLDEN_DIR = Path(__file__).parent / "golden"
MODEL = Path(__file__).resolve().parents[2] / "model-conversion" / "output" / "SigLIP2Vision.fp32.onnx"
COSINE_GATE = 0.999


@pytest.mark.skipif(not MODEL.exists(), reason="SigLIP2Vision.fp32.onnx not built")
def test_golden_vector():
    from PIL import Image

    from valueguard_daemon.classifier import Classifier

    image = np.asarray(Image.open(GOLDEN_DIR / "golden.png").convert("RGB"))
    reference = np.asarray(json.loads((GOLDEN_DIR / "golden_embedding.json").read_text()), dtype=np.float32)

    embedding = Classifier(MODEL, providers="cpu").embed(image)

    assert embedding.shape == reference.shape
    assert np.linalg.norm(embedding) == pytest.approx(1.0, abs=1e-3)
    cosine = float(np.dot(embedding, reference))
    assert cosine >= COSINE_GATE, f"cosine {cosine} below gate {COSINE_GATE}"
